### ISSUE TITLE
“Resetful” should be “RESTful”

### ISSUE THREAD

**Issue by tonyxu-io** [godruoyi/restful-api-specification#1]
This is critical issue, making readers consider this as extremely not professional at first glance.

**Comment by godruoyi** [comment]
thank you，has changed.

**Comment by tonyxu-io** [comment]
看了你刚刚的commit，没有改对。是REST，不是RESET。

**Comment by godruoyi** [comment]
😰😰，还真没注意这点，太丢脸啦:snail: :snail: :snail:

**Comment by tonyxu-io** [comment]
哈哈哈，没关系，文档写的挺好的
