### ISSUE TITLE
现有动词无法表示的情况，URL如何设计？

### ISSUE THREAD

**Issue by xwsg** [godruoyi/restful-api-specification#3]
比如`读取`通知消息，将通知消息置为`未读`，这两种情况应该如何表示？
目前做法是采用`PUT`
```
PUT /notifications/{nId}/read
PUT /notifications/{nId}/unread
```

**Comment by dummyhat** [comment]
`PUT /notifications/{nId}` 然后在实体里面传具体的状态信息吧

**Comment by godruoyi** [comment]
可以按照 @dummyhat  说的这种方式去实现呢，目前我采用的也是在 `请求体` 里加参数已区分

```http
PUT /notifications/{nId} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
cache-control: no-cache
Host: example.com
accept-encoding: gzip, deflate
Connection: keep-alive

type=read
```

**Comment by xwsg** [comment]
@dummyhat @godruoyi 多谢回复，那有没有将动作放在path中的情况呢？再比如：`导出`操作呢？
希望可以出一些`现有动词无法表示`情况的说明。
现在网上的各种规范基本都没有定义这部分。很多时候设计path的时候那真是很痛苦。

**Comment by dummyhat** [comment]
@xwsg `导出`可以看作是一种资源或服务吧，例如可以用`exports`
`GET /exports?type=xxxxx`

**Comment by xwsg** [comment]
@dummyhat  多谢，理解了，有时候对于`一切皆资源`这个观念还是不太好转变
