### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by harrisyang** [godruoyi/restful-api-specification#5]
Hello, 你好。对于API Versioning，有几点疑问请教下：

- 如何保持老版本与新版本的并存？如何管理？
- 在新版本发布后，老版本的生命周期是多少？何时废弃？
- 一般新版本的发布规律是怎么样的？何时升级版本？
- 请问有没有API版本控制的实战经验？如果当时project不是微服务，该如何操作？

Best regards

**Comment by harrisyang** [comment]
> Hello, 你好。对于API Versioning，有几点疑问请教下：
> 
> * 如何保持老版本与新版本的并存？如何管理？
> * 在新版本发布后，老版本的生命周期是多少？何时废弃？
> * 一般新版本的发布规律是怎么样的？何时升级版本？
>   -请问有没有API版本控制的实战经验？如果当时project不是微服务，该如何操作？

**Comment by godruoyi** [comment]
你好，关于如何保存新旧版本的共存，我们在项目中是这样做的；以 `Laravel` 为例，在 `Controllers` 下建立不同版本的文件夹，以放置不同版本的代码：
![image](https://user-images.githubusercontent.com/16079222/54520992-f37c8900-49a4-11e9-8286-adc0f208fb9f.png)

根据具体的项目需求，新版本发布后，若 `Client` 能全部换为新版本 `API`，那直接 `Remove` 旧版本也是可以的。

关于发布规律，目前我们也没有具体可循的规律，至于何时发布，可以参考 `语义化版本` 的定义：

- 主版本号：当你做了不兼容的 API 修改
- 次版本号：当你做了向下兼容的功能性新增
- 修订号：当你做了向下兼容的问题修正

> 当我们做了不兼容的 API 修改时，我们一般都会发布大版本（V1 - V2）

以上就是我理解的 API 版本控制了啦。😄

**Comment by harrisyang** [comment]
@godruoyi  Thanks for your quickly response.
有一点疑问：建立不同版本的文件夹时，你们是如何避免代码冗余？
尤其是build API response.

**Comment by godruoyi** [comment]
抱歉消息看漏了，这么晚才回复，

这确实时个问题，我们在升级版本的时候，控制层（controller）里的大部分代码都会弃用，服务能抽离的测抽离，不能抽离的，则允许它冗余，毕竟多个版本共存的项目中，这个没法控制。

还有就是不同的版本前端需要的 Response 格式可能不一致，我们目前的做法是尽量复用以前的 Response transformer，若涉及太大的变动，不能复用的，则重新创建新的 Response transformer。

你有什么好的建议吗，至少目前我们只能这样处理。

**Comment by harrisyang** [comment]
@godruoyi , thanks for your response.
目前我们也不能找到一种完美解决方案，现在的做法是避免高度耦合. 在一个project里做API versioning，代码冗余难免. 主要涉及点：
1. Request body/parameter的复用
2. Response body的复用
3. Code logic的复用
还在探索中...
