### ISSUE TITLE
url名字一样不利于前端在network查找开发

### ISSUE THREAD

**Issue by wumiangithub** [godruoyi/restful-api-specification#7]
GET | /zoos/{zoo} | 获取指定动物园详情
-- | -- | --
PUT | /zoos/{zoo} | 更新指定动物园(整个对象)

**Comment by godruoyi** [comment]
你可也通过 request method 来区分，

**Comment by chaunsin** [comment]
> GET	/zoos/{zoo}	获取指定动物园详情
> PUT	/zoos/{zoo}	更新指定动物园(整个对象)

我也是这么认为
